name: 
  remote_server
ssh_configuration: 
  remote_test
work_path:
  ~/experiments/
local_tmp_path:
  /tmp/auto_disc
execution:
  ./multi_seeds_run.sh $NB_SEEDS $ARGS
cancellation:
  for pid in $RUN_ID; do kill -9 $pid; done
check_experiment_launched_every:
  1